remote_theme: pmarsceill/just-the-docs@v0.1.6

title: Spotty
description: ''
baseurl: '/spotty'
url: ''

# build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# the theme settings
search_enabled: true
aux_links:
  GitHub:
    - https://github.com/apls777/spotty

webrick:
  headers:
    Access-Control-Allow-Origin: '*'
